# Generated by Django 5.1.6 on 2025-03-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobzikapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
