# Generated by Django 5.1.6 on 2025-03-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobzikapp', '0002_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
