# Generated by Django 5.1.6 on 2025-03-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobzikapp', '0004_alter_star_options_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
